### ISSUE TITLE
Ascending/Descending label is always displayed

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix-svelte-front-end#1]
When I'm scrolling down in the resource tree view, the ascending/descending label text from the history view is always displayed, but the history view in general "scrolls away", such that it's not displayed anymore.

![Screenshot from 2020-02-16 18-51-09](https://user-images.githubusercontent.com/1202851/74609814-fb313a00-50ed-11ea-9f3a-af45a83a674d.png)

**Comment by mosheduminer** [comment]
Hmm, I didn't notice that, thanks! That happens because that text has the `fixed` tailwind class, which applies `position: fixed`, which keeps the text at the same position on the window...

This could also be fixed by fixing the height of the components, so they never descend beyond the bottom of the screen. I have to look into that anyway.

**Comment by mosheduminer** [comment]
This issue has been fixed. However the current behavior is that the slider/switch text scrolls with the switch, perhaps it would be better for both the slider and the text to remain fixed in position (even after scroll)?

**Comment by JohannesLichtenberger** [comment]
Yeah, Maybe also the databases/resources on the left

**Comment by mosheduminer** [comment]
The dbsView, historyView, and resourceView scroll separately, and there is no longer any global scroll.

Additionally, with commit 2579210735f5381bf510a86c2a7a83a831ac5c03, the slider and associated text will always remain in the same position, with the history timeline scrolling underneath it.
